# Generated by Django 2.1.1 on 2019-07-12 21:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=400)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorinformation',
            name='rating',
        ),
        migrations.AddField(
            model_name='tutorinformation',
            name='phone_number',
            field=models.CharField(default='12049956727', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorinformation',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.UserInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='firebase_id',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='tutorreview',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TutorInformation'),
        ),
        migrations.AddField(
            model_name='tutorreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserInformation'),
        ),
    ]
